// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0mdXal5TqalRBViHimu_On_aNqhJcALw',
    appId: '1:121955424187:web:f55e1f61f12c553548d69e',
    messagingSenderId: '121955424187',
    projectId: 'librarymq-348b6',
    authDomain: 'librarymq-348b6.firebaseapp.com',
    databaseURL: 'https://librarymq-348b6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'librarymq-348b6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX6OTXieluRB4E5DepxwuzkMt66OinT78',
    appId: '1:121955424187:android:1e8112796e2e3ddb48d69e',
    messagingSenderId: '121955424187',
    projectId: 'librarymq-348b6',
    databaseURL: 'https://librarymq-348b6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'librarymq-348b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8ru9it3l8gCsDim5tbF2BXfXfXx-B1V0',
    appId: '1:121955424187:ios:7a822676a0da747548d69e',
    messagingSenderId: '121955424187',
    projectId: 'librarymq-348b6',
    databaseURL: 'https://librarymq-348b6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'librarymq-348b6.appspot.com',
    iosBundleId: 'com.example.mqLibraryApp',
  );

}